BEGIN;

ALTER TABLE reviews ADD COLUMN IF NOT EXISTS model TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS input_tokens INTEGER;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS output_tokens INTEGER;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS files_reviewed INTEGER;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS files_skipped INTEGER;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;

COMMIT;
