import axios from 'axios';
import express from 'express';
import pool from '../config/db';
import { AuthRequest, authenticateToken } from '../middleware/auth';
import { generateReview } from '../reviews/openaiReviewer';
import { prepareDiff } from '../reviews/prepareDiff';
import { GitHubPullRequestFile } from '../reviews/types';
import { AIReviewResult, ReviewSeverity } from '../reviews/types';
import { findingKey, validateFindings } from '../reviews/validateFindings';
import { decryptToken } from '../security/tokenEncryption';
import { reviewCreationRateLimit } from '../middleware/rateLimits';

const router = express.Router();
router.use(authenticateToken);

function positiveInteger(value: unknown): number | null {
  const number = Number(value);
  return Number.isInteger(number) && number > 0 ? number : null;
}

function reviewMarkdown(review: { pr_title: string; pr_number: number; analysis_result: AIReviewResult }) {
  const analysis = review.analysis_result;
  const findings = analysis.findings.length
    ? analysis.findings.map((finding) => [
      `### ${finding.severity === 'critical' ? '🔴' : finding.severity === 'high' ? '🟠' : finding.severity === 'medium' ? '🟡' : '🔵'} ${finding.title}`,
      `**${finding.category} · ${Math.round(finding.confidence * 100)}% confidence · \`${finding.file}${finding.line ? `:${finding.line}` : ''}\`**`,
      '', finding.description, '', `> Evidence: ${finding.evidence}`, '', `**Suggested fix:** ${finding.suggestion}`,
    ].join('\n')).join('\n\n---\n\n')
    : '✅ No evidence-backed findings met this repository’s review policy.';
  return [`## PullPilot review · PR #${review.pr_number}`, '', `**Risk: ${analysis.riskLevel}**`, '', analysis.summary, '', findings, '', '_Generated by PullPilot · Every displayed finding passed file, changed-line, confidence, and duplicate validation._'].join('\n');
}

router.get('/repository/:repoId', async (req: AuthRequest, res) => {
  const repoId = positiveInteger(req.params.repoId);
  if (!repoId) return res.status(400).json({ error: 'Invalid repository ID' });
  try {
    const repoCheck = await pool.query('SELECT id FROM repositories WHERE id = $1 AND user_id = $2', [repoId, req.userId]);
    if (repoCheck.rows.length === 0) return res.status(404).json({ error: 'Repository not found' });
    const result = await pool.query('SELECT * FROM reviews WHERE repository_id = $1 ORDER BY created_at DESC', [repoId]);
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching reviews:', error);
    res.status(500).json({ error: 'Failed to fetch reviews' });
  }
});

router.post('/', reviewCreationRateLimit, async (req: AuthRequest, res) => {
  const repositoryId = positiveInteger(req.body.repositoryId);
  const prNumber = positiveInteger(req.body.prNumber);
  if (!repositoryId || !prNumber) return res.status(400).json({ error: 'repositoryId and prNumber must be positive integers' });

  try {
    const repoResult = await pool.query(
      `SELECT r.*, u.access_token FROM repositories r JOIN users u ON r.user_id = u.id
       WHERE r.id = $1 AND r.user_id = $2`,
      [repositoryId, req.userId]
    );
    if (repoResult.rows.length === 0) return res.status(404).json({ error: 'Repository not found' });
    const repo = repoResult.rows[0];
    const accessToken = decryptToken(repo.access_token);
    const headers = { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json' };
    const prResponse = await axios.get(`https://api.github.com/repos/${repo.full_name}/pulls/${prNumber}`, { headers });
    const filesResponse = await axios.get<GitHubPullRequestFile[]>(
      `https://api.github.com/repos/${repo.full_name}/pulls/${prNumber}/files`,
      { headers, params: { per_page: 100 } }
    );
    const prepared = prepareDiff(filesResponse.data);
    const reviewResult = await pool.query(
      `INSERT INTO reviews (repository_id, pr_number, pr_title, status, files_reviewed, files_skipped)
       VALUES ($1, $2, $3, 'pending', $4, $5) RETURNING *`,
      [repositoryId, prNumber, prResponse.data.title, prepared.analyzedFiles.length, prepared.skippedFiles.length]
    );
    const review = reviewResult.rows[0];
    void processReview(review.id, prResponse.data.title, prepared, {
      instructions: repo.review_instructions || '',
      minimumConfidence: Number(repo.minimum_confidence ?? 0.65),
      minimumSeverity: (repo.minimum_severity || 'low') as ReviewSeverity,
    }).catch((error) => console.error(`Unexpected review processor failure for ${review.id}:`, error));
    res.status(201).json(review);
  } catch (error: any) {
    console.error('Error creating review:', error);
    if (error.response?.status === 404) return res.status(404).json({ error: 'Pull request not found' });
    res.status(500).json({ error: 'Failed to create review' });
  }
});

async function processReview(reviewId: number, prTitle: string, prepared: ReturnType<typeof prepareDiff>, policy: { instructions: string; minimumConfidence: number; minimumSeverity: ReviewSeverity }) {
  try {
    await pool.query('UPDATE reviews SET started_at = NOW() WHERE id = $1', [reviewId]);
    const generated = await generateReview(prTitle, prepared.prompt, policy.instructions);
    const validated = validateFindings(generated.result, prepared, policy);
    const analysis = { ...validated.result, metadata: { analyzedFiles: prepared.analyzedFiles, skippedFiles: prepared.skippedFiles, validation: validated.metadata } };
    await pool.query(
      `UPDATE reviews SET status = 'completed', analysis_result = $1, model = $2,
       input_tokens = $3, output_tokens = $4, validation_metadata = $5,
       completed_at = NOW(), error_message = NULL WHERE id = $6`,
      [JSON.stringify(analysis), generated.model, generated.inputTokens, generated.outputTokens, JSON.stringify(validated.metadata), reviewId]
    );
    console.log(`Review ${reviewId} completed with ${generated.model}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown review error';
    console.error(`Error analyzing review ${reviewId}:`, message);
    await pool.query(`UPDATE reviews SET status = 'failed', error_message = $1, completed_at = NOW() WHERE id = $2`, [message.slice(0, 500), reviewId]);
  }
}

router.get('/analytics/summary', async (req: AuthRequest, res) => {
  try {
    const result = await pool.query(
      `SELECT COUNT(DISTINCT rv.id)::int AS reviews,
       COUNT(ff.id)::int AS rated_findings,
       COUNT(ff.id) FILTER (WHERE ff.disposition = 'accepted')::int AS accepted,
       COUNT(ff.id) FILTER (WHERE ff.disposition = 'dismissed')::int AS dismissed
       FROM reviews rv
       JOIN repositories repo ON repo.id = rv.repository_id
       LEFT JOIN finding_feedback ff ON ff.review_id = rv.id AND ff.user_id = $1
       WHERE repo.user_id = $1 AND rv.status = 'completed'`,
      [req.userId]
    );
    const row = result.rows[0];
    const rated = Number(row.rated_findings || 0);
    res.json({ ...row, acceptance_rate: rated ? Math.round((Number(row.accepted) / rated) * 100) : null });
  } catch (error) {
    console.error('Error fetching review analytics:', error);
    res.status(500).json({ error: 'Failed to fetch review analytics' });
  }
});

router.post('/:id/findings/:findingIndex/feedback', async (req: AuthRequest, res) => {
  const id = positiveInteger(req.params.id);
  const findingIndex = Number(req.params.findingIndex);
  const disposition = req.body.disposition;
  const reason = typeof req.body.reason === 'string' ? req.body.reason.trim().slice(0, 500) : null;
  if (!id || !Number.isInteger(findingIndex) || findingIndex < 0) return res.status(400).json({ error: 'Invalid finding' });
  if (!['accepted', 'dismissed'].includes(disposition)) return res.status(400).json({ error: 'Invalid disposition' });
  try {
    const reviewResult = await pool.query(
      `SELECT rv.analysis_result FROM reviews rv JOIN repositories repo ON repo.id = rv.repository_id
       WHERE rv.id = $1 AND repo.user_id = $2`, [id, req.userId]
    );
    if (!reviewResult.rows.length) return res.status(404).json({ error: 'Review not found' });
    const finding = (reviewResult.rows[0].analysis_result as AIReviewResult)?.findings?.[findingIndex];
    if (!finding) return res.status(404).json({ error: 'Finding not found' });
    const result = await pool.query(
      `INSERT INTO finding_feedback (review_id, user_id, finding_key, disposition, reason)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (review_id, user_id, finding_key) DO UPDATE
       SET disposition = EXCLUDED.disposition, reason = EXCLUDED.reason, updated_at = NOW()
       RETURNING *`, [id, req.userId, findingKey(finding), disposition, reason]
    );
    res.json(result.rows[0]);
  } catch (error) {
    console.error('Error saving finding feedback:', error);
    res.status(500).json({ error: 'Failed to save feedback' });
  }
});

router.get('/:id/feedback', async (req: AuthRequest, res) => {
  const id = positiveInteger(req.params.id);
  if (!id) return res.status(400).json({ error: 'Invalid review ID' });
  try {
    const result = await pool.query(
      `SELECT ff.* FROM finding_feedback ff JOIN reviews rv ON rv.id = ff.review_id
       JOIN repositories repo ON repo.id = rv.repository_id
       WHERE ff.review_id = $1 AND ff.user_id = $2 AND repo.user_id = $2`, [id, req.userId]
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching feedback:', error);
    res.status(500).json({ error: 'Failed to fetch feedback' });
  }
});

router.post('/:id/publish', async (req: AuthRequest, res) => {
  const id = positiveInteger(req.params.id);
  if (!id) return res.status(400).json({ error: 'Invalid review ID' });
  try {
    const result = await pool.query(
      `SELECT rv.*, repo.full_name, u.access_token FROM reviews rv
       JOIN repositories repo ON repo.id = rv.repository_id JOIN users u ON u.id = repo.user_id
       WHERE rv.id = $1 AND repo.user_id = $2`, [id, req.userId]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Review not found' });
    const review = result.rows[0];
    if (review.status !== 'completed' || !review.analysis_result?.findings) return res.status(409).json({ error: 'Only completed structured reviews can be published' });
    if (review.github_comment_url) return res.json({ github_comment_url: review.github_comment_url, already_published: true });
    const response = await axios.post(
      `https://api.github.com/repos/${review.full_name}/issues/${review.pr_number}/comments`,
      { body: reviewMarkdown(review) },
      { headers: { Authorization: `Bearer ${decryptToken(review.access_token)}`, Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28' } }
    );
    await pool.query('UPDATE reviews SET github_comment_url = $1 WHERE id = $2', [response.data.html_url, id]);
    res.json({ github_comment_url: response.data.html_url });
  } catch (error: unknown) {
    const status = axios.isAxiosError(error) ? error.response?.status : undefined;
    console.error('Error publishing GitHub review:', error);
    if (status === 401 || status === 403) return res.status(403).json({ error: 'GitHub permission denied. Sign out and authorize PullPilot again to grant public repository access.' });
    res.status(500).json({ error: 'Failed to publish review to GitHub' });
  }
});

router.get('/:id', async (req: AuthRequest, res) => {
  const id = positiveInteger(req.params.id);
  if (!id) return res.status(400).json({ error: 'Invalid review ID' });
  try {
    const result = await pool.query(
      `SELECT r.* FROM reviews r JOIN repositories repo ON r.repository_id = repo.id
       WHERE r.id = $1 AND repo.user_id = $2`,
      [id, req.userId]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Review not found' });
    res.json(result.rows[0]);
  } catch (error) {
    console.error('Error fetching review:', error);
    res.status(500).json({ error: 'Failed to fetch review' });
  }
});

export default router;
